# Generated by Django 5.2.5 on 2026-03-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='Nome')),
                ('nickname', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Apelido')),
                ('profile_picture', models.ImageField(upload_to='media/profile_picture/', verbose_name='Apelido')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
