# Generated by Django 5.2.5 on 2026-03-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_picture/', verbose_name='Foto do usuário'),
        ),
    ]
