# Generated by Django 5.2.5 on 2026-03-26 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_users_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('nickname', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Apelido')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='media/profile_picture/', verbose_name='Foto do usuário')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfis',
                'verbose_name_plural': 'Perfil',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
